# ~/.config/fuzzel/fuzzel.ini

font=monospace:size=11
dpi-aware=auto
prompt="❯ "
icons-enabled=no
lines=8
width=35
horizontal-pad=15
vertical-pad=12
inner-pad=8

[colors]
# Format: RRGGBBAA
background=000409ff
text=ffffffb3
match=ffffffff
selection=ffffff22
selection-text=ffffffff
selection-match=ffffffff
border=ffffffff

[border]
width=1
radius=0
