#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Focus follows mouse movement
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#wallpaper
feh --bg-scale ~/Downloads/argonaut.png

#Autostart
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh &
volumeicon &
nm-applet &
xfce4-power-manager &

#disable touchpad
xinput disable "PS/2 Synaptics TouchPad"


