#!/bin/sh
exec 2>&1

export XDG_RUNTIME_DIR="/run/user/1000"
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

# Wait for PipeWire socket
while [ ! -S "$XDG_RUNTIME_DIR/pipewire-0" ]; do
    sleep 0.2
done

exec wireplumber
