# Swipe left with 3 fingers to go to the next desktop
gesture swipe left 3 bspc desktop -f next.local

# Swipe right with 3 fingers to go to the previous desktop
gesture swipe right 3 bspc desktop -f prev.local
