[color]
;; Your original colors
background = #292929
foreground = #bcbcbc
primary = #E7E7E7
alert = #f38ba8
disabled = #707880

;; Shade colors for the pills
shade1 = #353535
shade2 = #404040
shade3 = #454545
