[module/bspwm]
type = internal/bspwm
label-focused = %name%
label-focused-background = ${color.shade3}
label-focused-underline = ${color.primary}
label-focused-padding = 2
label-occupied = %name%
label-occupied-padding = 2
label-empty = 
label-urgent = %name%
label-urgent-background = ${color.alert}

[module/xwindow]
type = internal/xwindow

; Only show the title if a window is actually open
label = %title%
label-maxlen = 40
label-empty = Desktop
label-empty-foreground = ${color.disabled}

; Styling to match your bspwm look
label-background = ${color.shade3}
label-padding = 2

[module/date]
type = internal/date
interval = 5
date = %a %b %d, %I:%M %p
label = %date%
label-padding = 1

[module/cpu]
type = internal/cpu
format = <label>
format-prefix = " "
label = %percentage%%
label-padding = 1

[module/memory]
type = internal/memory
format = <label>
format-prefix = " "
label = %percentage_used%%
label-padding = 1

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <label-volume>
format-volume-prefix = " "
label-volume = %percentage%%
label-volume-padding = 1
format-muted = <label-muted>
format-muted-prefix = " "
label-muted = " Muted"

[module/network]
type = custom/script
exec = ~/.config/polybar/scripts/wifi.sh
tail = true

label = %output%

click-left = nm-connection-editor &
click-right = st -e nmtui &

[module/battery]
type = internal/battery

full-at = 97

battery = BAT1
adapter = ACAD
poll-interval = 2
time-format = %H:%M
format-charging = <label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 4
format-discharging = <ramp-capacity><label-discharging>
format-full =   Full
label-charging = %percentage%%
label-discharging =%percentage%%
label-full =%percentage%%
ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-font = 1

[module/temperature]
type = internal/temperature

# Seconds to sleep between updates
interval = 0.5

# Check the path found in step 1. 
# Usually /sys/class/thermal/thermal_zone0/temp
thermal-zone = 0

# Full path of temperature sysfs path
# Use `sensors` to find which hwmon path corresponds to your CPU
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp1_input

# Thresholds for colors
base-temperature = 20
warn-temperature = 60

# Formatting
format = <label>
format-warn = <label-warn>
label =  %temperature-c%
label-warn =  %temperature-c%
label-warn-foreground = #f00

[module/mpris]
type = custom/script
tail = true
interval = 1
format-prefix = "󰎆 "
format-background = ${color.shade3}
format-padding = 1

exec = ~/.config/polybar/scripts/scroll_music.sh
; Controls
click-left = playerctl play-pause
double-click-right = playerctl previous
click-right = playerctl next
